PROJECT_LIST = [
    {
        "slug": "soc-log-analyzer",
        "screenshot": "soc-log-analyzer.png",
        "title": "SOC Log Analyzer",
        "kind": "Software project",
        "kind_class": "software",
        "category": "Cybersecurity / SOC / Python / Flask",
        "pitch": "A security monitoring and log-analysis application that helps analysts examine authentication logs, identify suspicious activity, detect patterns and generate useful security reports.",
        "tech": ["Python", "Flask", "SQLite", "Bash", "HTML", "JavaScript", "Git"],
        "capabilities": [
            "Log parsing", "Failed login detection", "Authentication analysis",
            "Suspicious activity detection", "Security dashboards", "Reporting",
            "MITRE ATT&CK mapping", "IOC-related analysis",
        ],
        "github": "https://github.com/claudias94/SOC-log-analyzer",
        "cta": "View Project",
        "notice": None,
        "extras": None,
        "sections": [
            {"key": "problem", "title": "The Problem",
             "body": ["Authentication logs contain valuable evidence of attacks, but reading raw logs by hand is slow and it is easy to miss repeated failures or unusual patterns."]},
            {"key": "objective", "title": "The Objective",
             "body": ["Build an application that lets an analyst load authentication logs, see suspicious activity quickly and produce a report that others can act on."]},
            {"key": "approach", "title": "The Approach",
             "body": ["Parse raw log lines into structured records, store them in a database, apply detection logic for common patterns, and present the results in a dashboard and report. Findings are related to MITRE ATT&CK techniques so an analyst can see what a pattern may indicate."]},
            {"key": "tech", "title": "Technology", "body": []},
            {"key": "implementation", "title": "Implementation",
             "body": ["What the application was built to do:"],
             "items": ["Log parsing", "Failed login detection", "Authentication analysis",
                       "Suspicious activity detection", "Security dashboards", "Reporting",
                       "MITRE ATT&CK mapping", "IOC-related analysis"]},
            {"key": "security", "title": "Security Considerations",
             "body": ["Log content is untrusted input, so it needs to be validated and encoded before it is displayed. A tool that handles security data should also be careful about what it stores, who can see it and how its own dependencies are managed."]},
            {"key": "results", "title": "Results",
             "body": ["The project demonstrates a complete workflow from raw authentication logs to an analyst-readable report. It is a software project, and no claims are made about production use or real-world detections."]},
            {"key": "lessons", "title": "Lessons Learned",
             "body": ["Practical experience in parsing messy real-world log formats, deciding what counts as suspicious, and turning detections into output that a human can act on quickly."]},
            {"key": "future", "title": "Future Improvements",
             "body": ["Possible next steps:"],
             "items": ["Support for more log sources", "Configurable detection thresholds",
                       "Exportable report formats", "Role-based access to the dashboard"]},
        ],
    },
    {
        "slug": "cirt-lab",
        "screenshot": None,  # e.g. "cirt-lab.png" once uploaded
        "title": "Cyber Incident Response & Digital Forensics Lab",
        "kind": "Laboratory exercise",
        "kind_class": "lab",
        "category": "Cybersecurity / Incident Response / Digital Forensics",
        "pitch": "A practical isolated laboratory built to simulate the investigation and response process following a compromised system.",
        "tech": ["Ubuntu", "Metasploitable2", "Nmap", "Linux forensic collection",
                 "Windows forensic collection", "IOC database"],
        "capabilities": [],
        "github": None,
        "cta": "View Case Study",
        "notice": "This was performed in an isolated laboratory on systems built for the purpose. It is a controlled defensive exercise covering security testing, incident response, evidence collection and analysis. It is not a service that involves testing systems without authorisation.",
        "extras": {
            "environment_title": "Lab environment",
            "environment": ["Ubuntu", "Metasploitable2 (intentionally vulnerable test system)",
                            "Network reconnaissance", "Evidence collection",
                            "Linux forensic collection", "Windows forensic collection",
                            "IOC database", "Suspicious processes", "Suspicious ports",
                            "Incident investigation", "Reporting", "Evidence packaging"],
            "timeline": ["Environment preparation", "Reconnaissance",
                         "System compromise simulation", "Evidence collection",
                         "IOC analysis", "Suspicious activity investigation",
                         "Incident analysis", "Reporting", "Evidence packaging",
                         "Lessons learned"],
        },
        "sections": [
            {"key": "problem", "title": "The Problem",
             "body": ["When a system is compromised, the response has to be methodical: evidence must be collected before it is lost, and the investigation has to be documented. Practising this on real systems is not appropriate."]},
            {"key": "objective", "title": "The Objective",
             "body": ["Simulate a compromise in a safe, isolated environment and work through the full response process: investigate, collect evidence, analyse indicators and report."]},
            {"key": "approach", "title": "The Approach",
             "body": ["Build a closed lab network, simulate a compromise on a deliberately vulnerable target, then respond as an incident responder would, following the timeline shown above."]},
            {"key": "tech", "title": "Technology", "body": []},
            {"key": "implementation", "title": "Implementation",
             "body": ["The lab covered network reconnaissance, collection of forensic evidence from Linux and Windows systems, an IOC database, investigation of suspicious processes and ports, and packaging of evidence with a written report."]},
            {"key": "security", "title": "Security Considerations",
             "body": ["The environment was isolated from other networks, used only systems built for testing, and evidence was handled and packaged in an organised way so it could be reviewed later."]},
            {"key": "results", "title": "Results",
             "body": ["The exercise demonstrates an end-to-end incident response and forensics workflow, from preparation through to a packaged evidence set and report. It is a laboratory exercise and does not represent a real client incident."]},
            {"key": "lessons", "title": "Lessons Learned",
             "body": ["Practical experience in collecting evidence in a consistent order, correlating indicators across sources, and documenting each step so the investigation can be followed by someone else."]},
            {"key": "future", "title": "Future Improvements",
             "body": ["Possible next steps:"],
             "items": ["More automated evidence collection", "Additional operating systems and scenarios",
                       "Timeline reconstruction tooling", "A reusable incident report template"]},
        ],
    },
    {
        "slug": "kiams",
        "screenshot": None,  # e.g. "kiams.png" once uploaded
        "title": "KIAMS: Kenya School of Government Internal Information & Alert Management System",
        "kind": "Prototype",
        "kind_class": "prototype",
        "category": "Web Application / Internal Information System / Secure Software",
        "pitch": "A secure, centralized platform that replaces scattered WhatsApp announcements with an official, auditable, role-based notice board for KSG staff, built after observing this communication gap firsthand as an IT Officer at the Kenya School of Government.",
        "tech": ["Python", "Flask", "SQLite / PostgreSQL", "HTML", "CSS", "JavaScript", "REST APIs"],
        "capabilities": [],
        "github": None,
        "cta": "View Case Study",
        "notice": "KIAMS is a prototype developed to address an internal communication problem observed in an organizational environment. It is not an officially deployed or endorsed system of the Kenya School of Government.",
        "extras": None,
        "sections": [
            {"key": "problem", "title": "The Problem",
             "body": ["This problem was observed firsthand in day-to-day IT work at the Kenya School of Government, where important internal announcements were often shared through WhatsApp groups and other informal channels rather than an official system. Organizations that rely on this approach run into problems with:"],
             "items": ["Information visibility", "Message loss", "Accountability",
                       "Searching old notices", "Official communication",
                       "Access control", "Auditability"]},
            {"key": "objective", "title": "The Objective",
             "body": ["Design a centralized internal platform where authorized users can publish and receive official notices, with clear access control and a record of what was published and by whom."]},
            {"key": "approach", "title": "The Approach",
             "body": ["A role-based web application: authenticated users see the notices they are permitted to see, authorized publishers create them, and administrators manage users and settings. Actions are recorded in an audit trail."]},
            {"key": "tech", "title": "Technology", "body": []},
            {"key": "implementation", "title": "Implementation",
             "body": ["Core concepts in the prototype:"],
             "items": ["Role-based access", "Authentication", "Centralized notices",
                       "Priority announcements", "Audit trail", "Search",
                       "Categorization", "User management", "Secure access",
                       "Administrative controls"]},
            {"key": "security", "title": "Security Considerations",
             "body": ["Access is controlled by role, users authenticate before viewing notices, passwords must be stored hashed, and publishing actions are logged so they can be reviewed."]},
            {"key": "results", "title": "Results",
             "body": ["The prototype demonstrates how an official, searchable and auditable notice system can replace informal announcement channels. It has not been formally deployed."]},
            {"key": "lessons", "title": "Lessons Learned",
             "body": ["Practical experience in designing role-based access for an organizational setting, and in treating accountability and auditability as design requirements from the start."]},
            {"key": "future", "title": "Future Improvements",
             "body": ["Possible next steps:"],
             "items": ["Read receipts and acknowledgements", "Email or SMS notification options",
                       "Department-level targeting", "A formal security review before any real deployment"]},
        ],
    },
]

PROJECTS = {p["slug"]: p for p in PROJECT_LIST}

STACK = [
    ("Programming", ["Python", "JavaScript", "HTML", "CSS", "Bash"]),
    ("Frameworks", ["Flask"]),
    ("Databases", ["SQLite", "PostgreSQL"]),
    ("Security", ["Nmap", "Wireshark", "Gobuster", "SOC concepts", "Log analysis",
                  "Digital forensics", "Incident response", "IOC analysis"]),
    ("Systems", ["Ubuntu", "Kali Linux", "Windows", "Windows Server", "CentOS"]),
    ("Development", ["Git", "GitHub", "REST APIs", "JWT", "API security"]),
]
